version: "3"

services:
  web:
    build:
      context: .
      dockerfile: apps/web/Dockerfile
    restart: always
    ports:
      - 3000:3000
    networks:
      - app_network
  api:
    build:
      context: .
      dockerfile: apps/api/Dockerfile
    restart: always
    ports:
      - 3001:3001
    networks:
      - app_network
  sms:
    build:
      context: .
      dockerfile: apps/sms/Dockerfile
    restart: always
    ports:
      - 3002:3001
    networks:
      - app_network
  db:
    image: postgres
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    #volumes:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    environment:
      POSTGRES_PASSWORD: example
    ports:
      - 5432:5432
    network_mode: host
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

# Define a network, which allows containers to communicate
# with each other, by using their container name as a hostname
networks:
  app_network:
