import type { Metadata } from "next";
import {NextIntlClientProvider} from "next-intl";

export const metadata: Metadata = {
  title: "La-Ventil",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
    return (
        <html>
        <body>
        <NextIntlClientProvider>{children}</NextIntlClientProvider>
        </body>
        </html>
    );
}
