import type { Metadata } from 'next';
import { redirect } from 'next/navigation';
import BottomNavigation from '@repo/ui/bottom-navigation';
import { getServerSession } from '../../lib/auth';
import styles from './layout.module.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default async function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession();
  if (!session) {
    redirect('/login');
  }

  return (
    <>
      <main className={styles.main}>
        {children}
      </main>
      <footer>
        <BottomNavigation />
      </footer>
    </>
  );
}
