import type { Metadata } from "next";
import BottomNavigation from "@repo/ui/bottom-navigation";
import {getServerSession} from "../../lib/auth";
import {redirect} from "next/navigation";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
 const session = await getServerSession()
    if (!session) {
        redirect('/signin');
    }

  return <>
      <main>
          <pre>{JSON.stringify(session, null, 2)}</pre>
          {children}
      </main>
      <footer>
          <BottomNavigation />
      </footer>
  </>;
}
