import type { Metadata } from 'next';
import Image from 'next/image';
import { Typography } from '@mui/material';
import Link from '@repo/ui/link';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <Link href="/">
        <Image src="/vercel.svg" alt="Vercel logomark" width={20} height={20} />
        <Typography variant="h1">La-Ventil</Typography>
      </Link>
      {children}
    </>
  );
}
